# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

J_logistic_cpp <- function(X, beta) {
    .Call('_Biostat625_HW3_Joey_Junyi_Qiu_J_logistic_cpp', PACKAGE = 'Biostat625.HW3.Joey.Junyi.Qiu', X, beta)
}

