# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Logistic Regression Prediction Function
#' @description This function calculates the predicted probabilities using a logistic regression model.
#' @param X A numeric matrix where each row is an observation, and each column is a feature.
#' @param beta A numeric vector of coefficients for the logistic regression model.
#' @return A numeric vector of predicted probabilities.
#' @export
logistic <- function(X, beta) {
    .Call('_Biostat625_HW3_Joey_Junyi_Qiu_logistic', PACKAGE = 'Biostat625.HW3.Joey.Junyi.Qiu', X, beta)
}

